Debug
Signed-off-by: Sunjay Bhatia <sunjayb@vmware.com>

diff --git a/.github/workflows/build_daily.yaml b/.github/workflows/build_daily.yaml
--- a/.github/workflows/build_daily.yaml
+++ b/.github/workflows/build_daily.yaml
@@ -103,6 +103,8 @@ jobs:
           CONTOUR_E2E_IMAGE: ghcr.io/projectcontour/contour:main
           IPV6_CLUSTER: "true"
         run: |
+          cat /etc/docker/daemon.json || echo "/etc/docker/daemon.json not found"
+          make setup-kind-cluster
           ifconfig | grep inet6
           export CONTOUR_E2E_LOCAL_HOST=$(ifconfig | grep inet6 | grep -v link | grep -v host | head -n1 | awk '{print $2}')
           echo "CONTOUR_E2E_LOCAL_HOST=$CONTOUR_E2E_LOCAL_HOST"
